- .github/workflows/ci.yml
> Fix Invalid Event in CI Workflow

- client.bal
- tests/mysql_atomic_batch_execute_operation.bal
- tests/mysql_batch_execute_operation.bal
- tests/mysql_call_stored_procedures.bal
- tests/mysql_complex_type_queries.bal
- tests/mysql_execute_operation.bal
- tests/mysql_query_operation.bal
this is a temporary fix for the issue ballerina-platform/ballerina-lang#31290
> Add java dependency as an import to fix the issue temporary

- README.md
> Update readme for mysql.driver connector

- .github/workflows/ci.yml
- .github/workflows/release.yml
> Upgrade ballerina version

- README.md
> Update ballerina version in the README

- Ballerina.toml
> Upgrade package version

- Package.md
- README.md
$subject
Fixes: https://github.com/ballerina-platform/module-ballerinax-mysql.driver/issues/15
> Add license details of MySQL connector

- Ballerina.toml
> Update to next minor version

- .github/workflows/central-publish.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Ballerina.toml
- Package.md
- README.md
$subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2804
> Migrate to 2201.0.0

- ballerina/Package.md
> Change Slack reference to Discord

- ballerina/Ballerina.toml
- build-config/resources/Ballerina.toml
- build.gradle
- gradle.properties
> Update MySQL driver version to 8.0.31

- ballerina/Module.md
- ballerina/Package.md
> Update documentation to change MySQL driver version to 8.0.31

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- ballerina/Module.md
- ballerina/Package.md
- build-config/resources/Ballerina.toml
- gradle.properties
$subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/3736
> Bump minor version and update Ballerina lang to 2201.3.0

- native/src/main/resources/META-INF/native-image/io.ballerina.stdlib/mysql.driver-native/reflect-config.json
> $Subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3755
> Add missing native-image configs

- .github/pull_request_template.md
- .github/workflows/trivy-scan.yml
$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2927
> Trigger notification for trivy scan failure

- .github/workflows/trivy-scan.yml
> Fix notification trigger payload

- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/trivy-scan.yml
- README.md
- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- build-config/resources/Ballerina.toml
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- native/build.gradle
> Java17 migration

- ballerina/Dependencies.toml
- gradle.properties
> Update lang version to 2201.7.0

- .github/workflows/build-timestamped-master.yml
> Add timestamp build workflow

- .github/workflows/publish-release.yml
- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- ballerina/Module.md
- build-config/resources/Ballerina.toml
- gradle.properties
> Bump to the next minor version

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- gradle.properties
> Update mySQLDriver Java Dependency Version

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- gradle.properties
> Update connector version

- .github/workflows/build-timestamped-master.yml
- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/trivy-scan.yml
- README.md
- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- build-config/resources/Ballerina.toml
- gradle.properties
> Migrate to Java 21

- .github/workflows/build-timestamped-master.yml
> Update `upload-artifact` version

- gradle.properties
> Migrate to new Runtime APIs

- .github/workflows/build-timestamped-master.yml
- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/trivy-scan.yml
- README.md
- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- build-config/resources/Ballerina.toml
- gradle.properties
> Migrate to Java21

- ballerina/Dependencies.toml
- gradle.properties
> Prepare u11 release
